language: objective-c
osx_image: xcode611

env:
  matrix:
    - RUBY_TEST_VERSION="2.0"
    - RUBY_TEST_VERSION="Current"

matrix:
  allow_failures:
    - env: RUBY_TEST_VERSION="Current"
  fast_finish: true

before_install:
  - rvm use system
  - export PATH="/System/Library/Frameworks/Ruby.framework/Versions/${RUBY_TEST_VERSION}/usr/bin":"$PATH"
  - printenv PATH
  - brew update
  - brew upgrade > /dev/null
  - ruby --version
  - echo ls_ruby_bindir; ls "/System/Library/Frameworks/Ruby.framework/Versions/${RUBY_TEST_VERSION}/usr/bin"
  - which brew
  - brew --prefix
  - brew tap domt4/homebrew-tex
  - export PATH="/usr/texbin":"$PATH"
  - printenv PATH
  - sudo gem install mocha minitest
  - sudo mocha version
  - echo $PWD
  - curl -L http://mirrors.rit.edu/CTAN/systems/mac/mactex/mactex-basic.pkg -o mactex-basic.pkg
  - sudo installer -pkg mactex-basic.pkg -target /
script:
  - brew test-bot $TRAVIS_COMMIT
notifications:
    email: false
